"""Initial migration

Revision ID: 0d87ec95ccfa
Revises: 
Create Date: 2022-10-26 01:52:07.240051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d87ec95ccfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone_num', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('specialty', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accountants_email'), 'accountants', ['email'], unique=True)
    op.create_index(op.f('ix_accountants_name'), 'accountants', ['name'], unique=True)
    op.create_index(op.f('ix_accountants_phone_num'), 'accountants', ['phone_num'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_accountants_phone_num'), table_name='accountants')
    op.drop_index(op.f('ix_accountants_name'), table_name='accountants')
    op.drop_index(op.f('ix_accountants_email'), table_name='accountants')
    op.drop_table('accountants')
    # ### end Alembic commands ###
