"""empty message

Revision ID: 6e8bd5d21bbe
Revises: c6f31952b8af
Create Date: 2022-10-26 01:29:15.372327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8bd5d21bbe'
down_revision = 'c6f31952b8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountants',
    sa.Column('datetime', sa.String(length=128), nullable=False),
    sa.Column('sensor_1', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('datetime')
    )
    op.drop_table('machine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('datetime', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('sensor_1', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('datetime', name='machine_pkey')
    )
    op.drop_table('accountants')
    # ### end Alembic commands ###
